//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaylistCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlist
    {
        public long id { get; set; }
        public string name { get; set; }
        public bool favorite { get; set; }
        public string description { get; set; }
    }
}
