//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud_test_c
{
    using System;
    using System.Collections.Generic;
    
    public partial class playlist
    {
        public void Sets(playlist obj)
        {
            this.name = obj.name;
            this.favorite = obj.favorite;
            this.description = obj.description;
            this.index = obj.index;
        }
        public long id { get; set; }
        public string name { get; set; }
        public bool favorite { get; set; }
        public string description { get; set; }
        public Nullable<int> index { get; set; }
    }
}
